### ISSUE TITLE
NullPointException on fakeDataDao.selectAllUsers()

### ISSUE THREAD

**Issue by jpga89** [djdjalas/learning-spring-boot#1]
Hi! 

I'm debuggig and trying to solve this so I can continue with the course.

java.lang.NullPointerException
	at com.jpga.learningspringboot.service.UserServiceTest.shouldGetAllUsers(UserServiceTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)

Any idea why this is happening? 

Thanks!

**Comment by jpga89** [comment]
Solved. I had imported a different library from org.junit.Test
